version: '3.8'

services:
  my-mongodb:
    image: mongodb/mongodb-atlas-local:7.0.9
    container_name: ragd
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=myuser
      - MONGODB_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017