
sequenceDiagram
    participant User as User/System
    participant IndexService as Document Indexing Service
    participant TikaReader as Apache TikaReader
    participant TokenSplitter as TokenTextSplitter
    participant OpenAI as OpenAI Embedding Model
    participant MongoDB as MongoDB
    participant VectorStore as Vector Store

    User->>IndexService: Request Document Indexing
    IndexService->>IndexService: Check if Document Processed (Hash)
    alt If Processed
        IndexService->>User: Return Success

    end
    alt If Document is new
        IndexService->>processed_docs: Store document in processed_docs collection to mark as processed
        IndexService->>TikaReader: Load Document
        TikaReader-->>IndexService: Document Loaded
        IndexService->>TokenSplitter: Split Document into Chunks
        TokenSplitter-->>IndexService: Chunks Created
        IndexService->>OpenAI: Get Embedding for each Chunk
        OpenAI-->>IndexService: Embedding Retrieved
        IndexService->>VectorStore: Save Embedding in Vector Store
        IndexService->>User: Return Success
    end

    alt If Document is Updated
        IndexService->>processed_docs: Save updated document in processed_docs collection
        IndexService->>VectorStore: Delete Existing Embeddings
        IndexService->>TikaReader: Load Document
        TikaReader-->>IndexService: Document Loaded
        IndexService->>TokenSplitter: Split Document into Chunks
        TokenSplitter-->>IndexService: Chunks Created
        IndexService->>OpenAI: Get Embedding for each Chunk
        OpenAI-->>IndexService: Embedding Retrieved
        IndexService->>VectorStore: Save New Embedding in Vector Store
        IndexService->>User: Return Success
    end