spring:
  application:
    name: spring-ai-rag-app
  data:
    mongodb:
      uri: mongodb://myuser:password@localhost:27017/?directConnection=true
      database: ragdb
      auto-index-creation: true
      authentication-database: admin

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
          encoding-format: float
          path-name: embedding
          dimensions: 1536
    vectorstore:
      mongodb:
        initialize-schema: true
        collection-name: vector_store
        index-name: ragdb_ix
        path-name: embedding

logging:
  pattern:
    console: "[rag-app] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: INFO
